path:
    pdfs:       "db/pdfs/"
    trees:      "db/trees/"
    embeddings: "db/embeddings/"

chunker:
    size:       8000
    overlap:    2000

embeddings:
    base_url:        "http://localhost:8081"
    endpoint:        "/embeddings"
    timeout:         30
    template:        {'input': [], 'model': "", 'encoding_format': "float"}
    dimentions:      768
    document_prefix: "search_document: "
    query_prefix:    "search_query: "
    tokenizer_model: "models/tokenizer/nomic-ai/nomic-embed-text-v1.5"