path:
    pdfs:       "db/pdfs/"
    trees:      "db/trees/"
    embeddings: "db/embeddings/"

chunker:
    separators: ["\n\n",   "\n|",   ".", "!", "?",   "\n",   ",", " ",    ""]
    size:       2048
    overlap:    256

embeddings:
    base_url: "http://localhost:8081"
    endpoint: "/embeddings"
    timeout:  30
    template: {'input': [], 'model': "", 'encoding_format': "float"}
    size:     768